
# puppet forge modules
mod 'puppetlabs/stdlib'    , '6.4.0'
mod 'puppetlabs/vcsrepo'   , '3.1.0'
mod 'camptocamp/systemd'   , '2.7.0'
mod 'puppetlabs/inifile'   , '4.4.0'
mod 'puppetlabs/apt'       , '7.4.1'
mod 'puppetlabs/translate' , '2.2.0'
mod 'puppet/archive'       , '4.6.0'