
# puppet forge modules
mod 'puppetlabs/stdlib'    , '6.6.0'
mod 'puppetlabs/vcsrepo'   , '3.1.0'
mod 'puppet/systemd'       , '3.5.1'
mod 'puppetlabs/inifile'   , '4.4.0'
mod 'puppetlabs/apt'       , '8.3.0'
mod 'puppet/archive'       , '5.0.0'
mod 'puppetlabs/java'      , '7.3.0'